export const DEFAULT_EMBEDDING_PROVIDER = 'newapi';

const DEFAULT_AIHUB_MODEL = process.env.AIHUB_DEFAULT_MODEL || 'glm-5.1';

export const DEFAULT_MODEL = DEFAULT_AIHUB_MODEL;
export const DEFAULT_PROVIDER = 'newapi';
export const DEFAULT_MINI_MODEL = DEFAULT_AIHUB_MODEL;
export const DEFAULT_MINI_PROVIDER = 'newapi';

export const DEFAULT_ONBOARDING_MODEL = DEFAULT_AIHUB_MODEL;
export const DEFAULT_ONBOARDING_PROVIDER = 'newapi';
