apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../test
  - auth-signup-ingress.yaml
  - ingress.yaml
  - metadata-egress-network-policy.yaml
  - oidc-token-ingress.yaml
  - webapi-trace-ingress.yaml
