apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: masterino-oidc-token-ingress
  namespace: masterino-test
  labels:
    app.kubernetes.io/name: masterino
    app.kubernetes.io/part-of: masterino
    masterino.io/environment: test
  annotations:
    nginx.ingress.kubernetes.io/limit-rpm: '5'
    nginx.ingress.kubernetes.io/limit-burst-multiplier: '1'
    nginx.ingress.kubernetes.io/proxy-body-size: '16k'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/proxy-hide-headers: >-
      X-Middleware-Rewrite, X-Middleware-Set-Cookie, X-Nextjs-Cache,
      X-Nextjs-Matched-Path, X-Nextjs-Prerender, X-Nextjs-Rewritten-Path,
      X-Nextjs-Rewritten-Query, X-Nextjs-Stale-Time, X-Invoke-Path,
      X-Invoke-Query, X-Invoke-Output, X-Powered-By
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - mlai-test.bielcrystal.com
      secretName: 20261122bielcrystal.com
  rules:
    - host: mlai-test.bielcrystal.com
      http:
        paths:
          - path: /oidc/token
            pathType: Exact
            backend:
              service:
                name: masterino
                port:
                  number: 3210
