apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: masterino
resources:
  - ../../base
  - auth-signup-ingress.yaml
  - namespace.yaml
  - configmap.yaml
  - ingress.yaml
  - metadata-egress-network-policy.yaml
  - oidc-token-ingress.yaml
  - webapi-trace-ingress.yaml
replicas:
  - name: masterino
    count: 1
