apiVersion: v1
kind: Namespace
metadata:
  name: masterlion
  labels:
    app.kubernetes.io/part-of: masterlion
    masterlion.io/environment: production
  annotations:
    masterlion.io/ack-cluster-id: c5c81a41c33164f578f4e43a77fda5fc3
    masterlion.io/ack-region: cn-shenzhen
